name: Sync README.md to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  sync:
    name: Sync README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v1

      - name: Sync README
        uses: ms-jpq/sync-dockerhub-readme@e2991ea1ba48832e73555cdbd5b82f5a2e91ee9b # v1
        with:
          username: icingaadmin
          password: '${{ secrets.DOCKER_HUB_PERSONAL_TOKEN }}'
          repository: icinga/icinga2
          readme: ./README.md
